### ISSUE TITLE
Add migrate, seed, rollback to package.json

### ISSUE THREAD

**Issue by ba5eem** [lyricnrhyme/eeden#10]
remember to make the life easier for your teammates, include scripts for migrate and seed: 

```
POSTGRES_HOSTNAME=localhost POSTGRES_CONTAINER_PORT=5432 POSTGRES_USER=user POSTGRES_DB=dbname POSTGRES_PASSWORD=dbpassword npx knex --knexfile ./server/knexfile.js migrate:latest
```

**Comment by rcjmedia** [comment]
Scripts has been added, thanks!

`    "migrate": "POSTGRES_HOSTNAME=localhost POSTGRES_CONTAINER_PORT=5432 npx knex migrate:latest",
    "seed": "POSTGRES_HOSTNAME=localhost POSTGRES_CONTAINER_PORT=5432  npx knex seed:run",
   "flushdb": "POSTGRES_HOSTNAME=localhost POSTGRES_CONTAINER_PORT=5432 npx knex migrate:rollback ; POSTGRES_HOSTNAME=localhost POSTGRES_CONTAINER_PORT=5432 npx knex migrate:latest, POSTGRES_HOSTNAME=localhost POSTGRES_CONTAINER_PORT=5432 npx knex seed:run"
`
