### ISSUE TITLE
Readme - directions

### ISSUE THREAD

**Issue by ba5eem** [lyricnrhyme/eeden#6]
The readme has no getting started directions, the readme is like a map to get going on your project - think about all the times you wished a repo had a good readme to understand what is happening.

**Comment by hkotak** [comment]
@lyricnrhyme @JEFrady Since the three of use are touching most of the front end we need to develop a readme for anyone who comes to our repo so they can better understand what our app is about

**Comment by JEFrady** [comment]
@hkotak Ok, do you know what happened to the readme branch? It'll probably be a good starting point to start editing from
